name: Native CI

on: push

jobs:

  verify:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22.0.1'
          distribution: 'graalvm-community'
          cache: 'maven'
          native-image-job-reports: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Info
        run: mvn -version
      - name: Start Database
        run: ./docker/start_db.sh
      - name: test
        run: mvn test
      - name: package-native
        run: mvn package -Dpackaging=native-image
      - name: start-native
        run: ./target/demo &
      - name: wait
        run: sleep 1
      - name: test-version
        run: curl -v --fail http://localhost:8080/version
      - name: test-version
        run: curl -v --fail http://localhost:8080/order
